#SPDX-License-Identifier: MIT-0
---
# tasks file for nginx_role
- name: Install nginx
  ansible.builtin.package:
    name: "{{ nginx_package }}"
    state: present

- name: Copy index.html to web root
  ansible.builtin.copy:
    src: index.html
    dest: "{{ nginx_root }}/index.html"

- name: Configure nginx using template
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx

- name: Ensure nginx is started and enabled
  ansible.builtin.service:
    name: "{{ nginx_package }}"
    state: started
    enabled: true
